"""Sample Migration for Reference

Revision ID: 6d72b9ba9c08
Revises: 
Create Date: 2025-11-24 12:49:30.502984

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from src import settings

# revision identifiers, used by Alembic.
revision: str = '6d72b9ba9c08'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('modified_on', sa.DateTime(), nullable=False),
    sa.Column('required_uuid', sa.Uuid(), nullable=False),
    sa.Column('optional_uuid', sa.Uuid(), nullable=True),
    sa.Column('string_field', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('optional_text', sa.Text(), nullable=True),
    sa.Column('required_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('optional_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('big_int', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema=settings.database_schema
    )
    op.create_index(op.f('ix_test_schema_sample_table_id'), 'sample_table', ['id'], unique=False, schema=settings.database_schema)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_schema_sample_table_id'), table_name='sample_table', schema=settings.database_schema)
    op.drop_table('sample_table', schema=settings.database_schema)
    # ### end Alembic commands ###
